---
- name: install nginx
  apt: name=nginx state=latest update_cache=yes cache_valid_time={{cache_valid_seconds}}

- name: install nginx config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  register: nginx_config

- name: reload-nginx if config changed
  service: name=nginx state=reloaded
  when: nginx_config.changed

- name: make sure nginx is enabled and running
  service: name=nginx state=started enabled=true
